# Generated by Django 6.0.5 on 2026-06-10 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_orderproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='color',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='size',
        ),
    ]
